#if !os(tvOS)
import IssaUI
import SwiftUI

/// The standing disclosure under an answer: this was written by a machine, and
/// the machine was this one.
///
/// Apple's guidance for generative features is a small, permanent label rather
/// than a one-off alert — a reader who dismissed a warning three chapters ago
/// is reading this paragraph with nothing on screen to say where it came from —
/// and "Generated by Apple Intelligence" is the wording Foundation Models apps
/// have settled on. "On device" is added because it is the fact worth stating:
/// the sentence above was composed by a model on this hardware, and the
/// question that produced it never left the building.
///
/// Neutral rather than tinted, in `BetaPill`'s proportions: it is a caption
/// about the answer, not a control, and it must never compete with the answer
/// it sits beneath.
struct AskOriginPill: View {
    var body: some View {
        HStack(spacing: Metrics.spacing4) {
            Image(systemName: "sparkles")
            Text("Generated on device · Apple Intelligence")
        }
        .font(Typography.caption)
        .foregroundStyle(Palette.inkTertiary)
        .padding(.horizontal, Metrics.spacing8)
        .padding(.vertical, Metrics.spacing4 / 2)
        .background(Palette.surface, in: Capsule())
        .overlay(Capsule().strokeBorder(Palette.border, lineWidth: 1))
        // One phrase, not a glyph and a sentence read separately — and the
        // middle dot is punctuation VoiceOver has no good reading of.
        .accessibilityElement(children: .ignore)
        .accessibilityLabel("Generated on device by Apple Intelligence")
    }
}
#endif
