#if !os(tvOS)
import IssaAsk
import IssaUI
import SwiftUI

/// The standing disclosure in the Ask sheet: where the words come from.
///
/// Apple's guidance for generative features is a small, permanent label rather
/// than a one-off alert — a reader who dismissed a warning three chapters ago is
/// reading this paragraph with nothing on screen to say where it came from — and
/// "Generated by Apple Intelligence" is the wording Foundation Models apps have
/// settled on. "On device" is added because it is the fact worth stating: the
/// sentence above was composed by a model on this hardware, and the question
/// that produced it never left the building.
///
/// **Shown before the question as well as after the answer.** It used to appear
/// only once an answer existed, so nothing said "on device" while the reader
/// was deciding whether to type at all — which is the moment the fact matters
/// most, and the only moment at which it could change their mind. The wording
/// differs there because the claim has to: nothing has been generated yet, so
/// the pill states what the feature *is* rather than what it did.
///
/// Neutral rather than tinted, in `BetaPill`'s proportions: it is a caption
/// about the answer, not a control, and it must never compete with the answer it
/// sits beneath.
struct AskOriginPill: View {
    let state: AskOriginState

    var body: some View {
        if let label = AskOriginLabel.forState(state) {
            HStack(spacing: Metrics.spacing4) {
                Image(systemName: label.glyph)
                Text(label.phrase)
            }
            .font(Typography.caption)
            .foregroundStyle(Palette.inkTertiary)
            // The shared recipe, not a second copy of the same two numbers —
            // see `askPill`, which is where the two pills stopped agreeing.
            .askPill(Palette.surface)
            .overlay(Capsule().strokeBorder(Palette.border, lineWidth: 1))
            // One phrase, not a glyph and a sentence read separately — and the
            // middle dot is punctuation VoiceOver has no good reading of.
            .accessibilityElement(children: .ignore)
            .accessibilityLabel(label.spoken)
        }
    }
}

// MARK: -

/// Where the sheet is when the pill is drawn.
///
/// Two cases rather than the four the sheet has, because the pill only ever
/// answers one question — "who wrote what is on screen?" — and three of the
/// four states have written nothing. A failure gets no pill at all: a
/// provenance badge under "Something went wrong" is a claim about text that
/// does not exist.
enum AskOriginState: Equatable {
    /// Nothing has been answered yet: a blank field, or a question still being
    /// worked out. The pill still appears, saying what the feature will do.
    case unanswered
    /// An answer is on screen, and this is where it came from.
    case answered(AskAnswer.Origin)
}

/// What the disclosure says, and whether there is one at all.
///
/// The pill used to appear under **every** answered state, and two of the three
/// have no model behind them. `AskAnswerParser.notYetSentinel` is a constant in
/// this repo, emitted without any model call and also substituted over a
/// generated answer by the vetting pass; and `KinshipExtractor`'s sentence is a
/// name read straight out of a paragraph the reader has already passed. So the
/// pill claimed a machine had written a refusal nobody generated, and claimed
/// credit for the book's own words.
///
/// The book's own words get a quieter label rather than none, because that is
/// not the lesser answer — it is the strongest one this feature gives, the only
/// one whose citation is provably the sentence it came from, and a reader is
/// better served by being told so than by an AI disclosure.
///
/// Beside the view rather than inside it because `IssaSharedTests` cannot reach
/// a SwiftUI `View`, and "the pill must not appear over a refusal" is exactly
/// the sort of thing that comes back.
struct AskOriginLabel: Equatable {
    var glyph: String
    var phrase: String
    /// One sentence for VoiceOver, since the glyph and the middle dot read
    /// badly on their own.
    var spoken: String

    /// Nil where nothing should be said at all.
    static func forState(_ state: AskOriginState) -> AskOriginLabel? {
        switch state {
        case .unanswered:
            // No verb in the past tense anywhere in it. The answered label says
            // "Generated", which is a claim about words on screen; before there
            // are any, the only honest thing to say is where the work will
            // happen — and that is what a reader deciding whether to type
            // wants to know.
            AskOriginLabel(
                glyph: "sparkles",
                phrase: "On device · Apple Intelligence",
                spoken: "Answers are worked out on this device by Apple Intelligence",
            )
        case .answered(.model):
            AskOriginLabel(
                glyph: "sparkles",
                phrase: "Generated on device · Apple Intelligence",
                spoken: "Generated on device by Apple Intelligence",
            )
        case .answered(.book):
            // Quotation marks, not a book: what is above it is the book's own
            // sentence, and the mark for that is the one prose uses.
            AskOriginLabel(
                glyph: "text.quote",
                phrase: "From the book",
                spoken: "Taken from the book's own words",
            )
        case .answered(.withheld):
            nil
        }
    }
}
#endif
