#if !os(tvOS)
import IssaAsk
import IssaUI
import SwiftUI

/// The standing disclosure under an answer: who wrote the words above it.
///
/// Apple's guidance for generative features is a small, permanent label rather
/// than a one-off alert — a reader who dismissed a warning three chapters ago is
/// reading this paragraph with nothing on screen to say where it came from — and
/// "Generated by Apple Intelligence" is the wording Foundation Models apps have
/// settled on. "On device" is added because it is the fact worth stating: the
/// sentence above was composed by a model on this hardware, and the question
/// that produced it never left the building.
///
/// Neutral rather than tinted, in `BetaPill`'s proportions: it is a caption
/// about the answer, not a control, and it must never compete with the answer it
/// sits beneath.
struct AskOriginPill: View {
    let origin: AskAnswer.Origin

    var body: some View {
        if let label = AskOriginLabel.forOrigin(origin) {
            HStack(spacing: Metrics.spacing4) {
                Image(systemName: label.glyph)
                Text(label.phrase)
            }
            .font(Typography.caption)
            .foregroundStyle(Palette.inkTertiary)
            .padding(.horizontal, Metrics.spacing8)
            .padding(.vertical, Metrics.spacing4 / 2)
            .background(Palette.surface, in: Capsule())
            .overlay(Capsule().strokeBorder(Palette.border, lineWidth: 1))
            // One phrase, not a glyph and a sentence read separately — and the
            // middle dot is punctuation VoiceOver has no good reading of.
            .accessibilityElement(children: .ignore)
            .accessibilityLabel(label.spoken)
        }
    }
}

// MARK: -

/// What the disclosure says, and whether there is one at all.
///
/// The pill used to appear under **every** answered state, and two of the three
/// have no model behind them. `AskAnswerParser.notYetSentinel` is a constant in
/// this repo, emitted without any model call and also substituted over a
/// generated answer by the vetting pass; and `KinshipExtractor`'s sentence is a
/// name read straight out of a paragraph the reader has already passed. So the
/// pill claimed a machine had written a refusal nobody generated, and claimed
/// credit for the book's own words.
///
/// The book's own words get a quieter label rather than none, because that is
/// not the lesser answer — it is the strongest one this feature gives, the only
/// one whose citation is provably the sentence it came from, and a reader is
/// better served by being told so than by an AI disclosure.
///
/// Beside the view rather than inside it because `IssaSharedTests` cannot reach
/// a SwiftUI `View`, and "the pill must not appear over a refusal" is exactly
/// the sort of thing that comes back.
struct AskOriginLabel: Equatable {
    var glyph: String
    var phrase: String
    /// One sentence for VoiceOver, since the glyph and the middle dot read
    /// badly on their own.
    var spoken: String

    /// Nil where nothing should be said at all.
    static func forOrigin(_ origin: AskAnswer.Origin) -> AskOriginLabel? {
        switch origin {
        case .model:
            AskOriginLabel(
                glyph: "sparkles",
                phrase: "Generated on device · Apple Intelligence",
                spoken: "Generated on device by Apple Intelligence",
            )
        case .book:
            // Quotation marks, not a book: what is above it is the book's own
            // sentence, and the mark for that is the one prose uses.
            AskOriginLabel(
                glyph: "text.quote",
                phrase: "From the book",
                spoken: "Taken from the book's own words",
            )
        case .withheld:
            nil
        }
    }
}
#endif
